CREATE TABLE `CHAT_TB` (
  `MSG_SEQ` int(10) NOT NULL,
  `USER_SEQ` int(10) NOT NULL,
  PRIMARY KEY (`MSG_SEQ`),
  KEY `USER_FK` (`USER_SEQ`),
  CONSTRAINT `CHAT_FK` FOREIGN KEY (`MSG_SEQ`) REFERENCES `MSG_MST_TB` (`MSG_SEQ`) ON DELETE CASCADE,
  CONSTRAINT `USER_FK` FOREIGN KEY (`USER_SEQ`) REFERENCES `USER_MST_TB` (`USER_SEQ`) ON DELETE CASCADE
)