CREATE TABLE `USER_MST_TB` (
  `USER_SEQ` int(5) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(15) NOT NULL,
  `USER_PW` varchar(128) NOT NULL,
  `REG_DATETIME` varchar(14) DEFAULT NULL,
  `UPD_DATETIME` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`USER_SEQ`),
  UNIQUE KEY `USER_ID` (`USER_ID`)
) 